name: Terraform Deployment to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_VERSION: '1.5.6' # Adjust the version as per your requirement
  WORKING_DIRECTORY: './1_basic' # Path to your Terraform configuration directory
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Authenticate to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ env.AZURE_CLIENT_SECRET }}

    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform plan -out main.tfplan

    - name: Terraform Apply
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform apply main.tfplan
      run: terraform apply -auto-approve tfplan
